baseURL = 'https://esempio.it/'
languageCode = 'it-it'
title = 'Nuovo Progetto'
theme = 'PaperMod'

[params]
    # Indichiamo a PaperMod dove sono i post per la Home Page
    mainSections = ["posts"]

    # Opzioni specifiche per PaperMod
    defaultTheme = "auto"
    showCodeCopyButtons = true
    showReadingTime = true
    displayFullLangName = true

    [params.homeInfoParams]
        Title = "Benvenuto nel nuovo progetto"
        Content = "Lo scheletro della piattaforma è pronto. Puoi iniziare a creare contenuti in content/posts/."